### ISSUE TITLE
Can not load profile.ps1

### ISSUE THREAD

**Issue by yooakim** [Microsoft/WhackWhackTerminal#5] opened 2017-08-10 08:53 UTC
First; Thanks for developing this! The terminal in Visual Studio have alaways been sub-standard. This looks very promising!

When I launch the terminal I says my system does not allow running scripts. 
![capture](https://user-images.githubusercontent.com/862546/29162573-242364d8-7dba-11e7-84b9-d594f6b2d12e.PNG)

But this setting for `ExecutionPolicy` on my machine is is `RemoteSigned` - so I am wondering. Why would WhatWhackTerminal behave differently than the standard PowerShell terminal in terms of the permission?

**Comment by dgriffen** [comment] 2017-08-10 15:55
Right, so this is caused by the fact that the powershell that I launch is the 32bit version. The 32bit powershell and the 64bit powershell have different execution policies. The reason I launched the 32-bit version was because VS is 32bit and that was what was on the path at the time. An upcoming release will fix this issue and the code to fix it was actually checked in with #4. As a workaround until the new release you can always run `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser` from the terminal window.

**Closed by dgriffen** 2017-08-10 15:55 UTC
